name: CI/CD pipeline

on:
  push:
    branches:
      - develop
      - main
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  working-directory: ./ReviewService

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4
      - run: pwd

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test

      - name: Extract version from csproj
        id: get_version
        run: |
          VERSION=$(grep '<AssemblyVersion>' ReviewService.csproj | sed -E 's/.*<AssemblyVersion>(.*)<\/AssemblyVersion>.*/\1/')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
        working-directory: ${{ env.working-directory }}

      - name: Build Docker image
        run: docker build -t bukiteasy/review-service:${{ github.sha }} .
    
    outputs:
      VERSION: ${{ env.VERSION }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    if: success() #&& github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      - run: pwd

      - name: Build Docker image
        run: docker build -t bukiteasy/review-service:${{ github.sha }} .

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Docker image
        run: |
          IMAGE_TAG=${{ needs.build.outputs.VERSION }}
          docker tag bukiteasy/review-service:${{ github.sha }} bukiteasy/review-service:$IMAGE_TAG
          docker push bukiteasy/review-service:$IMAGE_TAG
  
  version:
    permissions: write-all
    runs-on: ubuntu-latest
    needs:
      - build
      - publish
    if: success() #&& github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.build.outputs.VERSION }}
          release_name: Release ${{ needs.build.outputs.VERSION }}
          body: |
            Changes in this release:
            - Description of changes
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}